export const leetcodeTopics = [
  "Array",
  "String",
  "Hash Table",
  "Dynamic Programming",
  "Math",
  "Sorting",
  "Greedy",
  "Depth-First Search",
  "Binary Search",
  "Database",
  "Breadth-First Search",
  "Tree",
  "Matrix",
  "Two Pointers",
  "Bit Manipulation",
  "Stack",
  "Heap (Priority Queue)",
  "Graph",
  "Linked List",
  "Backtracking",
  "Sliding Window",
  "Union Find",
  "Trie",
  "Design",
  "Recursion",
  "Simulation",
  "Divide and Conquer",
  "Queue",
  "Memoization",
  "Topological Sort",
  "Bitmask",
  "Geometry",
  "Segment Tree",
  "Binary Indexed Tree",
  "Number Theory",
  "Interactive",
  "Game Theory",
  "Data Stream",
  "String Matching",
  "Rolling Hash",
  "Shortest Path",
  "Combinatorics",
  "Randomized",
  "Probability and Statistics",
  "Suffix Array",
  "Concurrency",
  // --- Added: important CP/DSA topics ---
  "Prefix Sum",
  "Difference Array",
  "Monotonic Stack",
  "Monotonic Queue",
  "Binary Search on Answer",
  "Sparse Table",
  "Meet in the Middle",
  "Line Sweep",
  "Coordinate Compression",
  "Minimum Spanning Tree",
  "Strongly Connected Components",
  "Articulation Points and Bridges",
  "Bipartite Graph",
  "Network Flow",
  "Heavy Light Decomposition",
  "Euler Tour",
  "Centroid Decomposition",
  "KMP Algorithm",
  "Z-Algorithm",
  "Manacher's Algorithm",
  "Convex Hull",
  "Interval DP",
  "Digit DP",
  "Bitmask DP",
  "Tree DP",
  "Matrix Exponentiation",
  "Fast Fourier Transform",
  "Two Sum Pattern",
  "Cycle Detection",
  "Reservoir Sampling",
];

export const codeforcesTopics = [
  "Implementation",
  "Math",
  "Greedy",
  "DP",
  "Data Structures",
  "Brute Force",
  "Graphs",
  "Sortings",
  "Binary Search",
  "Trees",
  "Strings",
  "Number Theory",
  "Geometry",
  "Combinatorics",
  "DFS and similar",
  "Hashing",
  "Shortest Paths",
  "Two Pointers",
  "Bitmasks",
  "Constructive algorithms",
  "Interactive",
  "String suffix structures",
  "Probabilities",
  "Flows",
  "Matrices",
  "Games",
  "FFT",
  "Schedules",
  // --- Added: important CP topics ---
  "Prefix Sums",
  "Difference Arrays",
  "Segment Tree",
  "Sparse Table",
  "Binary Indexed Tree",
  "Monotonic Stack",
  "Monotonic Queue",
  "Sliding Window",
  "Meet in the Middle",
  "Ternary Search",
  "Divide and Conquer",
  "Coordinate Compression",
  "Convex Hull",
  "Line Sweep",
  "Minimum Spanning Tree",
  "Strongly Connected Components",
  "Articulation Points and Bridges",
  "Bipartite Matching",
  "Binary Lifting",
  "Heavy Light Decomposition",
  "Euler Tour",
  "Centroid Decomposition",
  "KMP / Z-Function",
  "Manacher's Algorithm",
  "Interval DP",
  "Digit DP",
  "Tree DP",
  "Matrix Exponentiation",
  "Cycle Detection",
  "Union Find",
]; 