export const leetcodeTopics = [
  "Array",
  "String",
  "Hash Table",
  "Dynamic Programming",
  "Math",
  "Sorting",
  "Greedy",
  "Depth-First Search",
  "Binary Search",
  "Database",
  "Breadth-First Search",
  "Tree",
  "Matrix",
  "Two Pointers",
  "Bit Manipulation",
  "Stack",
  "Heap (Priority Queue)",
  "Graph",
  "Linked List",
  "Backtracking",
  "Sliding Window",
  "Union Find",
  "Trie",
  "Design",
  "Recursion",
  "Simulation",
  "Divide and Conquer",
  "Queue",
  "Memoization",
  "Topological Sort",
  "Bitmask",
  "Geometry",
  "Segment Tree",
  "Binary Indexed Tree",
  "Number Theory",
  "Interactive",
  "Game Theory",
  "Data Stream",
  "String Matching",
  "Rolling Hash",
  "Shortest Path",
  "Combinatorics",
  "Randomized",
  "Probability and Statistics",
  "Suffix Array",
  "Concurrency",
];

export const codeforcesTopics = [
  "Implementation",
  "Math",
  "Greedy",
  "DP",
  "Data Structures",
  "Brute Force",
  "Graphs",
  "Sortings",
  "Binary Search",
  "Trees",
  "Strings",
  "Number Theory",
  "Geometry",
  "Combinatorics",
  "DFS and similar",
  "Hashing",
  "Shortest Paths",
  "Two Pointers",
  "Bitmasks",
  "Constructive algorithms",
  "Interactive",
  "String suffix structures",
  "Probabilities",
  "Flows",
  "Matrices",
  "Games",
  "FFT",
  "Schedules",
]; 